
package ru.dpd.ws.calculator._2012_03_20;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DPDCalculatorService", targetNamespace = "http://dpd.ru/ws/calculator/2012-03-20", wsdlLocation = "http://ws.dpd.ru/services/calculator2?wsdl")
public class DPDCalculatorService
    extends Service
{

    private final static URL DPDCALCULATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException DPDCALCULATORSERVICE_EXCEPTION;
    private final static QName DPDCALCULATORSERVICE_QNAME = new QName("http://dpd.ru/ws/calculator/2012-03-20", "DPDCalculatorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ws.dpd.ru/services/calculator2?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DPDCALCULATORSERVICE_WSDL_LOCATION = url;
        DPDCALCULATORSERVICE_EXCEPTION = e;
    }

    public DPDCalculatorService() {
        super(__getWsdlLocation(), DPDCALCULATORSERVICE_QNAME);
    }

    public DPDCalculatorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DPDCALCULATORSERVICE_QNAME, features);
    }

    public DPDCalculatorService(URL wsdlLocation) {
        super(wsdlLocation, DPDCALCULATORSERVICE_QNAME);
    }

    public DPDCalculatorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DPDCALCULATORSERVICE_QNAME, features);
    }

    public DPDCalculatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DPDCalculatorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DPDCalculator
     */
    @WebEndpoint(name = "DPDCalculatorPort")
    public DPDCalculator getDPDCalculatorPort() {
        return super.getPort(new QName("http://dpd.ru/ws/calculator/2012-03-20", "DPDCalculatorPort"), DPDCalculator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DPDCalculator
     */
    @WebEndpoint(name = "DPDCalculatorPort")
    public DPDCalculator getDPDCalculatorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dpd.ru/ws/calculator/2012-03-20", "DPDCalculatorPort"), DPDCalculator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DPDCALCULATORSERVICE_EXCEPTION!= null) {
            throw DPDCALCULATORSERVICE_EXCEPTION;
        }
        return DPDCALCULATORSERVICE_WSDL_LOCATION;
    }

}
