
package ru.dpd.ws.calculator._2012_03_20;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DPDCalculator", targetNamespace = "http://dpd.ru/ws/calculator/2012-03-20")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DPDCalculator {


    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<ru.dpd.ws.calculator._2012_03_20.ServiceCost>
     * @throws ServiceCostFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServiceCostByParcels", targetNamespace = "http://dpd.ru/ws/calculator/2012-03-20", className = "ru.dpd.ws.calculator._2012_03_20.GetServiceCostByParcels")
    @ResponseWrapper(localName = "getServiceCostByParcelsResponse", targetNamespace = "http://dpd.ru/ws/calculator/2012-03-20", className = "ru.dpd.ws.calculator._2012_03_20.GetServiceCostByParcelsResponse")
    @Action(input = "http://dpd.ru/ws/calculator/2012-03-20/DPDCalculator/getServiceCostByParcelsRequest", output = "http://dpd.ru/ws/calculator/2012-03-20/DPDCalculator/getServiceCostByParcelsResponse", fault = {
        @FaultAction(className = ServiceCostFault_Exception.class, value = "http://dpd.ru/ws/calculator/2012-03-20/DPDCalculator/getServiceCostByParcels/Fault/ServiceCostFault")
    })
    public List<ServiceCost> getServiceCostByParcels(
        @WebParam(name = "request", targetNamespace = "")
        ServiceCostParcelsRequest request)
        throws ServiceCostFault_Exception
    ;

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<ru.dpd.ws.calculator._2012_03_20.ServiceCost>
     * @throws ServiceCostFault2_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServiceCostByParcels2", targetNamespace = "http://dpd.ru/ws/calculator/2012-03-20", className = "ru.dpd.ws.calculator._2012_03_20.GetServiceCostByParcels2")
    @ResponseWrapper(localName = "getServiceCostByParcels2Response", targetNamespace = "http://dpd.ru/ws/calculator/2012-03-20", className = "ru.dpd.ws.calculator._2012_03_20.GetServiceCostByParcels2Response")
    @Action(input = "http://dpd.ru/ws/calculator/2012-03-20/DPDCalculator/getServiceCostByParcels2Request", output = "http://dpd.ru/ws/calculator/2012-03-20/DPDCalculator/getServiceCostByParcels2Response", fault = {
        @FaultAction(className = ServiceCostFault2_Exception.class, value = "http://dpd.ru/ws/calculator/2012-03-20/DPDCalculator/getServiceCostByParcels2/Fault/ServiceCostFault2")
    })
    public List<ServiceCost> getServiceCostByParcels2(
        @WebParam(name = "request", targetNamespace = "")
        ServiceCostParcelsRequest request)
        throws ServiceCostFault2_Exception
    ;

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<ru.dpd.ws.calculator._2012_03_20.ServiceCostInternational>
     * @throws ServiceCostFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServiceCostInternational", targetNamespace = "http://dpd.ru/ws/calculator/2012-03-20", className = "ru.dpd.ws.calculator._2012_03_20.GetServiceCostInternational")
    @ResponseWrapper(localName = "getServiceCostInternationalResponse", targetNamespace = "http://dpd.ru/ws/calculator/2012-03-20", className = "ru.dpd.ws.calculator._2012_03_20.GetServiceCostInternationalResponse")
    @Action(input = "http://dpd.ru/ws/calculator/2012-03-20/DPDCalculator/getServiceCostInternationalRequest", output = "http://dpd.ru/ws/calculator/2012-03-20/DPDCalculator/getServiceCostInternationalResponse", fault = {
        @FaultAction(className = ServiceCostFault_Exception.class, value = "http://dpd.ru/ws/calculator/2012-03-20/DPDCalculator/getServiceCostInternational/Fault/ServiceCostFault")
    })
    public List<ServiceCostInternational> getServiceCostInternational(
        @WebParam(name = "request", targetNamespace = "")
        ServiceCostInternationalRequest request)
        throws ServiceCostFault_Exception
    ;

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<ru.dpd.ws.calculator._2012_03_20.ServiceCost>
     * @throws ServiceCostFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServiceCost", targetNamespace = "http://dpd.ru/ws/calculator/2012-03-20", className = "ru.dpd.ws.calculator._2012_03_20.GetServiceCost")
    @ResponseWrapper(localName = "getServiceCostResponse", targetNamespace = "http://dpd.ru/ws/calculator/2012-03-20", className = "ru.dpd.ws.calculator._2012_03_20.GetServiceCostResponse")
    @Action(input = "http://dpd.ru/ws/calculator/2012-03-20/DPDCalculator/getServiceCostRequest", output = "http://dpd.ru/ws/calculator/2012-03-20/DPDCalculator/getServiceCostResponse", fault = {
        @FaultAction(className = ServiceCostFault_Exception.class, value = "http://dpd.ru/ws/calculator/2012-03-20/DPDCalculator/getServiceCost/Fault/ServiceCostFault")
    })
    public List<ServiceCost> getServiceCost(
        @WebParam(name = "request", targetNamespace = "")
        ServiceCostRequest request)
        throws ServiceCostFault_Exception
    ;

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<ru.dpd.ws.calculator._2012_03_20.ServiceCost>
     * @throws ServiceCostFault2_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServiceCost2", targetNamespace = "http://dpd.ru/ws/calculator/2012-03-20", className = "ru.dpd.ws.calculator._2012_03_20.GetServiceCost2")
    @ResponseWrapper(localName = "getServiceCost2Response", targetNamespace = "http://dpd.ru/ws/calculator/2012-03-20", className = "ru.dpd.ws.calculator._2012_03_20.GetServiceCost2Response")
    @Action(input = "http://dpd.ru/ws/calculator/2012-03-20/DPDCalculator/getServiceCost2Request", output = "http://dpd.ru/ws/calculator/2012-03-20/DPDCalculator/getServiceCost2Response", fault = {
        @FaultAction(className = ServiceCostFault2_Exception.class, value = "http://dpd.ru/ws/calculator/2012-03-20/DPDCalculator/getServiceCost2/Fault/ServiceCostFault2")
    })
    public List<ServiceCost> getServiceCost2(
        @WebParam(name = "request", targetNamespace = "")
        ServiceCostRequest request)
        throws ServiceCostFault2_Exception
    ;

}
