
package ru.dpd.ws.geography._2012_04_17;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DPDGeography", targetNamespace = "http://dpd.ru/ws/geography/2012-04-17")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DPDGeography {


    /**
     * 
     * @param auth
     * @return
     *     returns java.util.List<ru.dpd.ws.geography._2012_04_17.TerminalDPD>
     * @throws WSFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTerminalsSelfDelivery", targetNamespace = "http://dpd.ru/ws/geography/2012-04-17", className = "ru.dpd.ws.geography._2012_04_17.GetTerminalsSelfDelivery")
    @ResponseWrapper(localName = "getTerminalsSelfDeliveryResponse", targetNamespace = "http://dpd.ru/ws/geography/2012-04-17", className = "ru.dpd.ws.geography._2012_04_17.GetTerminalsSelfDeliveryResponse")
    @Action(input = "http://dpd.ru/ws/geography/2012-04-17/DPDGeography/getTerminalsSelfDeliveryRequest", output = "http://dpd.ru/ws/geography/2012-04-17/DPDGeography/getTerminalsSelfDeliveryResponse", fault = {
        @FaultAction(className = WSFault_Exception.class, value = "http://dpd.ru/ws/geography/2012-04-17/DPDGeography/getTerminalsSelfDelivery/Fault/WSFault")
    })
    public List<TerminalDPD> getTerminalsSelfDelivery(
        @WebParam(name = "auth", targetNamespace = "")
        Auth auth)
        throws WSFault_Exception
    ;

    /**
     * 
     * @param auth
     * @return
     *     returns java.util.List<ru.dpd.ws.geography._2012_04_17.DpdTerminalExt>
     * @throws WSFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTerminalsSelfDelivery2", targetNamespace = "http://dpd.ru/ws/geography/2012-04-17", className = "ru.dpd.ws.geography._2012_04_17.GetTerminalsSelfDelivery2")
    @ResponseWrapper(localName = "getTerminalsSelfDelivery2Response", targetNamespace = "http://dpd.ru/ws/geography/2012-04-17", className = "ru.dpd.ws.geography._2012_04_17.GetTerminalsSelfDelivery2Response")
    @Action(input = "http://dpd.ru/ws/geography/2012-04-17/DPDGeography/getTerminalsSelfDelivery2Request", output = "http://dpd.ru/ws/geography/2012-04-17/DPDGeography/getTerminalsSelfDelivery2Response", fault = {
        @FaultAction(className = WSFault_Exception.class, value = "http://dpd.ru/ws/geography/2012-04-17/DPDGeography/getTerminalsSelfDelivery2/Fault/WSFault")
    })
    public List<DpdTerminalExt> getTerminalsSelfDelivery2(
        @WebParam(name = "auth", targetNamespace = "")
        Auth auth)
        throws WSFault_Exception
    ;

    /**
     * 
     * @param auth
     * @return
     *     returns java.util.List<ru.dpd.ws.geography._2012_04_17.City>
     * @throws WSFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCitiesCashPay", targetNamespace = "http://dpd.ru/ws/geography/2012-04-17", className = "ru.dpd.ws.geography._2012_04_17.GetCitiesCashPay")
    @ResponseWrapper(localName = "getCitiesCashPayResponse", targetNamespace = "http://dpd.ru/ws/geography/2012-04-17", className = "ru.dpd.ws.geography._2012_04_17.GetCitiesCashPayResponse")
    @Action(input = "http://dpd.ru/ws/geography/2012-04-17/DPDGeography/getCitiesCashPayRequest", output = "http://dpd.ru/ws/geography/2012-04-17/DPDGeography/getCitiesCashPayResponse", fault = {
        @FaultAction(className = WSFault_Exception.class, value = "http://dpd.ru/ws/geography/2012-04-17/DPDGeography/getCitiesCashPay/Fault/WSFault")
    })
    public List<City> getCitiesCashPay(
        @WebParam(name = "auth", targetNamespace = "")
        Auth auth)
        throws WSFault_Exception
    ;

    /**
     * 
     * @param request
     * @return
     *     returns ru.dpd.ws.geography._2012_04_17.DpdParcelShops
     * @throws WSFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getParcelShops", targetNamespace = "http://dpd.ru/ws/geography/2012-04-17", className = "ru.dpd.ws.geography._2012_04_17.GetParcelShops")
    @ResponseWrapper(localName = "getParcelShopsResponse", targetNamespace = "http://dpd.ru/ws/geography/2012-04-17", className = "ru.dpd.ws.geography._2012_04_17.GetParcelShopsResponse")
    @Action(input = "http://dpd.ru/ws/geography/2012-04-17/DPDGeography/getParcelShopsRequest", output = "http://dpd.ru/ws/geography/2012-04-17/DPDGeography/getParcelShopsResponse", fault = {
        @FaultAction(className = WSFault_Exception.class, value = "http://dpd.ru/ws/geography/2012-04-17/DPDGeography/getParcelShops/Fault/WSFault")
    })
    public DpdParcelShops getParcelShops(
        @WebParam(name = "request", targetNamespace = "")
        DpdParcelShopRequest request)
        throws WSFault_Exception
    ;

}
