
package ru.dpd.ws.geography._2012_04_17;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DPDGeographyService", targetNamespace = "http://dpd.ru/ws/geography/2012-04-17", wsdlLocation = "http://ws.dpd.ru/services/geography?wsdl")
public class DPDGeographyService
    extends Service
{

    private final static URL DPDGEOGRAPHYSERVICE_WSDL_LOCATION;
    private final static WebServiceException DPDGEOGRAPHYSERVICE_EXCEPTION;
    private final static QName DPDGEOGRAPHYSERVICE_QNAME = new QName("http://dpd.ru/ws/geography/2012-04-17", "DPDGeographyService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ws.dpd.ru/services/geography?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DPDGEOGRAPHYSERVICE_WSDL_LOCATION = url;
        DPDGEOGRAPHYSERVICE_EXCEPTION = e;
    }

    public DPDGeographyService() {
        super(__getWsdlLocation(), DPDGEOGRAPHYSERVICE_QNAME);
    }

    public DPDGeographyService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DPDGEOGRAPHYSERVICE_QNAME, features);
    }

    public DPDGeographyService(URL wsdlLocation) {
        super(wsdlLocation, DPDGEOGRAPHYSERVICE_QNAME);
    }

    public DPDGeographyService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DPDGEOGRAPHYSERVICE_QNAME, features);
    }

    public DPDGeographyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DPDGeographyService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DPDGeography
     */
    @WebEndpoint(name = "DPDGeographyPort")
    public DPDGeography getDPDGeographyPort() {
        return super.getPort(new QName("http://dpd.ru/ws/geography/2012-04-17", "DPDGeographyPort"), DPDGeography.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DPDGeography
     */
    @WebEndpoint(name = "DPDGeographyPort")
    public DPDGeography getDPDGeographyPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dpd.ru/ws/geography/2012-04-17", "DPDGeographyPort"), DPDGeography.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DPDGEOGRAPHYSERVICE_EXCEPTION!= null) {
            throw DPDGEOGRAPHYSERVICE_EXCEPTION;
        }
        return DPDGEOGRAPHYSERVICE_WSDL_LOCATION;
    }

}
